name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      # * DISPLAY BRANCHES
      - name: Display Branches
        run: |
          echo "Current Branch: ${{ github.ref_name }}"

      # * AUTHENTIACTION (PRIVATE REPOSITORY)
      - name: Set Flag - Github Token
        id: gh_token
        run: |
          if [ -n "${{ secrets.GH_RETESTIFY_TEST_NTC_TOKEN }}" ]; then
            echo "gh_token=true" >> $GITHUB_OUTPUT
          else
            echo "gh_token=false" >> $GITHUB_OUTPUT
          fi
      - name: Git Authentication
        if: ${{ steps.gh_token.outputs.gh_token == 'true'}}
        run: |
          echo "Machine Github.com Login ${{ steps.gh_token.outputs.gh_token }}" > ~/.netrc
          chmod 600 ~/.netrc
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GH_RETESTIFY_TEST_NTC_TOKEN }}

      - run: pnpm install
      - run: pnpm lint && pnpm build
